- hosts: localhost
  any_errors_fatal: true

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.mysql.yml

  vars:
    epel_package_state: present
    apache_user: apache

  tasks:
    - block:
      - name: re-enable console access if debugging
        service:
          name: getty@tty1
          state: started
        when: debug is defined
      - import_tasks: tasks/robertdebock.httpd.yml
      - import_tasks: tasks/robertdebock.mysql.yml
      - import_tasks: tasks/packages_php7.yml
      - import_tasks: tasks/prov.yml
